In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from concept_benchmark.paths import results_dir

demo_results_dir = results_dir / "big_demo"
sudoku_results = "conceptual_safeguards_sudoku.csv"
robot_results = "score_intervention_robot.csv"

In [8]:
sudoku_df = pd.read_csv(demo_results_dir / sudoku_results)
robot_df = pd.read_csv(demo_results_dir / robot_results)

In [9]:
coverage = sudoku_df[sudoku_df['metric'].str.contains('coverage')]
coverage['type'] = coverage['metric'].str.split('_').str[1]

/tmp/ipykernel_546/1252860592.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coverage['type'] = coverage['metric'].str.split('_').str[1]

In [10]:
coverage[(coverage['tau'] == 0.05) & (coverage['split'] == 'test') & (coverage['type'] == 'before')].tail(20)

,strategy,metric,value,split,data_name,data_type,concept_noise,concept_missing,concept_missing_mech,target_accuracy_label,target_accuracy_value,tau,type
1705,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.25,0.30,mcar,easy,1.0,0.05,before
1729,conceptual_safeguards,coverage_before,0.927,test,sudoku,tabular,0.25,0.05,mnar,easy,1.0,0.05,before
1753,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.25,0.10,mnar,easy,1.0,0.05,before
1777,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.25,0.15,mnar,easy,1.0,0.05,before
1801,conceptual_safeguards,coverage_before,0.989,test,sudoku,tabular,0.25,0.20,mnar,easy,1.0,0.05,before
1825,conceptual_safeguards,coverage_before,0.989,test,sudoku,tabular,0.25,0.25,mnar,easy,1.0,0.05,before
1849,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.25,0.30,mnar,easy,1.0,0.05,before
1873,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.00,none,easy,1.0,0.05,before
1897,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.05,mcar,easy,1.0,0.05,before
1921,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.10,mcar,easy,1.0,0.05,before
1945,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.15,mcar,easy,1.0,0.05,before
1969,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.20,mcar,easy,1.0,0.05,before
1993,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.25,mcar,easy,1.0,0.05,before
2017,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.30,mcar,easy,1.0,0.05,before
2041,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.05,mnar,easy,1.0,0.05,before
2065,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.10,mnar,easy,1.0,0.05,before
2089,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.15,mnar,easy,1.0,0.05,before
2113,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.20,mnar,easy,1.0,0.05,before
2137,conceptual_safeguards,coverage_before,1.000,test,sudoku,tabular,0.30,0.25,mnar,easy,1.0,0.05,before
2161,conceptual_safeguards,coverage_before,0.996,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05,before

In [11]:
selective_acc = sudoku_df[sudoku_df['metric'].str.contains('selective')]
selective_acc['type'] = selective_acc['metric'].str.split('_').str[-1]

/tmp/ipykernel_546/861983395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selective_acc['type'] = selective_acc['metric'].str.split('_').str[-1]

In [12]:
selective_acc[(selective_acc['tau'] == 0.05) & (selective_acc['split'] == 'test') & (selective_acc['concept_noise'] > 0.1)]

,strategy,metric,value,split,data_name,data_type,concept_noise,concept_missing,concept_missing_mech,target_accuracy_label,target_accuracy_value,tau,type
936,conceptual_safeguards,selective_acc_before,0.979079,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05,before
938,conceptual_safeguards,selective_acc_after,0.989879,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05,after
960,conceptual_safeguards,selective_acc_before,0.792703,test,sudoku,tabular,0.15,0.05,mcar,easy,1.0,0.05,before
962,conceptual_safeguards,selective_acc_after,0.875000,test,sudoku,tabular,0.15,0.05,mcar,easy,1.0,0.05,after
984,conceptual_safeguards,selective_acc_before,0.796902,test,sudoku,tabular,0.15,0.10,mcar,easy,1.0,0.05,before
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114,conceptual_safeguards,selective_acc_after,0.500000,test,sudoku,tabular,0.30,0.20,mnar,easy,1.0,0.05,after
2136,conceptual_safeguards,selective_acc_before,0.500000,test,sudoku,tabular,0.30,0.25,mnar,easy,1.0,0.05,before
2138,conceptual_safeguards,selective_acc_after,0.500000,test,sudoku,tabular,0.30,0.25,mnar,easy,1.0,0.05,after
2160,conceptual_safeguards,selective_acc_before,0.502008,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05,before
2162,conceptual_safeguards,selective_acc_after,0.504000,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05,after

In [13]:
sudoku_df[(sudoku_df['tau'] == 0.05) & (sudoku_df['split'] == 'test') & (sudoku_df['concept_noise'] > 0.1)]

,strategy,metric,value,split,data_name,data_type,concept_noise,concept_missing,concept_missing_mech,target_accuracy_label,target_accuracy_value,tau
936,conceptual_safeguards,selective_acc_before,0.979079,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05
937,conceptual_safeguards,coverage_before,0.478000,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05
938,conceptual_safeguards,selective_acc_after,0.989879,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05
939,conceptual_safeguards,coverage_after,0.988000,test,sudoku,tabular,0.15,0.00,none,easy,1.0,0.05
960,conceptual_safeguards,selective_acc_before,0.792703,test,sudoku,tabular,0.15,0.05,mcar,easy,1.0,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...
2139,conceptual_safeguards,coverage_after,1.000000,test,sudoku,tabular,0.30,0.25,mnar,easy,1.0,0.05
2160,conceptual_safeguards,selective_acc_before,0.502008,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05
2161,conceptual_safeguards,coverage_before,0.996000,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05
2162,conceptual_safeguards,selective_acc_after,0.504000,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05
2163,conceptual_safeguards,coverage_after,1.000000,test,sudoku,tabular,0.30,0.30,mnar,easy,1.0,0.05

In [6]:
sudoku_df[(sudoku_df['concept_noise'] == 0.0) & (sudoku_df['split'] == 'test') & (sudoku_df['concept_missing'] == 0.3)]

,strategy,metric,value,split,data_name,data_type,concept_noise,concept_missing,concept_missing_mech,target_accuracy_label,target_accuracy_value,tau
292,conceptual_safeguards,selective_acc_before,0.995511,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.05
293,conceptual_safeguards,coverage_before,0.891000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.05
294,conceptual_safeguards,selective_acc_after,0.995803,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.05
295,conceptual_safeguards,coverage_after,0.953000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.05
300,conceptual_safeguards,selective_acc_before,0.991543,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.10
301,conceptual_safeguards,coverage_before,0.946000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.10
302,conceptual_safeguards,selective_acc_after,0.991820,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.10
303,conceptual_safeguards,coverage_after,0.978000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.10
308,conceptual_safeguards,selective_acc_before,0.987539,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.15
309,conceptual_safeguards,coverage_before,0.963000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.15
310,conceptual_safeguards,selective_acc_after,0.987854,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.15
311,conceptual_safeguards,coverage_after,0.988000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.15
316,conceptual_safeguards,selective_acc_before,0.987642,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.20
317,conceptual_safeguards,coverage_before,0.971000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.20
318,conceptual_safeguards,selective_acc_after,0.987903,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.20
319,conceptual_safeguards,coverage_after,0.992000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.20
324,conceptual_safeguards,selective_acc_before,0.986680,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.25
325,conceptual_safeguards,coverage_before,0.976000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.25
326,conceptual_safeguards,selective_acc_after,0.986895,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.25
327,conceptual_safeguards,coverage_after,0.992000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.25
332,conceptual_safeguards,selective_acc_before,0.986748,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.30
333,conceptual_safeguards,coverage_before,0.981000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.30
334,conceptual_safeguards,selective_acc_after,0.985915,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.30
335,conceptual_safeguards,coverage_after,0.994000,test,sudoku,tabular,0.0,0.3,mcar,easy,1.0,0.30
580,conceptual_safeguards,selective_acc_before,0.979675,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.05
581,conceptual_safeguards,coverage_before,0.492000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.05
582,conceptual_safeguards,selective_acc_after,0.984051,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.05
583,conceptual_safeguards,coverage_after,0.627000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.05
588,conceptual_safeguards,selective_acc_before,0.948365,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.10
589,conceptual_safeguards,coverage_before,0.581000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.10
590,conceptual_safeguards,selective_acc_after,0.961929,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.10
591,conceptual_safeguards,coverage_after,0.788000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.10
596,conceptual_safeguards,selective_acc_before,0.937309,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.15
597,conceptual_safeguards,coverage_before,0.654000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.15
598,conceptual_safeguards,selective_acc_after,0.952710,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.15
599,conceptual_safeguards,coverage_after,0.867000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.15
604,conceptual_safeguards,selective_acc_before,0.926129,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.20
605,conceptual_safeguards,coverage_before,0.731000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.20
606,conceptual_safeguards,selective_acc_after,0.941112,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.20
607,conceptual_safeguards,coverage_after,0.917000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.20
612,conceptual_safeguards,selective_acc_before,0.916137,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.25
613,conceptual_safeguards,coverage_before,0.787000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.25
614,conceptual_safeguards,selective_acc_after,0.931866,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.25
615,conceptual_safeguards,coverage_after,0.954000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.25
620,conceptual_safeguards,selective_acc_before,0.907341,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.30
621,conceptual_safeguards,coverage_before,0.831000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.30
622,conceptual_safeguards,selective_acc_after,0.922131,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.30
623,conceptual_safeguards,coverage_after,0.976000,test,sudoku,tabular,0.0,0.3,mnar,easy,1.0,0.30